/* -----------------------------------------------------------------;
 * $source   : / $
 * $revision : 1.0 $
 * $author   : wyr@null.co.za $
 * $date     : 2017/11/08 00:00:00 $
 * $desc     : $
 * $log      : $
 *
 * -----------------------------------------------------------------;
 */

package clipackage;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;
import java.io.*;
import java.io.IOException;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class gi_cli extends javax.swing.JFrame {    
   
    DefaultListModel  listModel;   
    public String     fileID;
    public JTextField txtField;
    
    /**
     * Creates new form ContactEditor
     */
    public gi_cli() {
        
        listModel = new DefaultListModel();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gli");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("gli"));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
/**
        listModel = new DefaultListModel();
        listModel.addElement("Item 1");
        listModel.addElement("Item 2");
        listModel.addElement("Item 3");
        listModel.addElement("Item 4");
        //creating J List
        jList1 = new JList(listModel);
        jScrollPane1.setViewportView(jList1);
**/
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Text");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(3, 3, 3)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(2, 2, 2)
                        .add(jTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(jButton4))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jButton1, jButton4}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jButton4)
                        .add(0, 0, Short.MAX_VALUE))))
        );

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("pp");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {

            getAlpha();
            
        } catch (IOException ex) {
            Logger.getLogger(gi_cli.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        defined_word_by_ai = "";
        global_count       = 0;
        
        jTextField5.setText("");
        
        DefaultListModel listModel = (DefaultListModel) jList1.getModel();
        listModel.removeAllElements();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {  
        System.exit(0);
    }
    
    // -------------------------------------------------------------------------;
    
    public static int randInt(int min, int max) 
    {
        Random rand   = new Random();
        int    r      = rand.nextInt((max - min) + 1) + min;
        
        return r;
    }

 
    // -------------------------------------------------------------------------;

    String defined_word_by_ai = "";
    int    global_count       = 0;
    
    private void getAlpha () throws FileNotFoundException, IOException
    {
        
        String e = null;
        String t = jTextField5.getText();
        
        BufferedReader br = new BufferedReader(new FileReader(System.getProperty("user.dir") + "/word/word.txt"));
        
        try {
            
            StringBuilder sb = new StringBuilder();
            String line      = br.readLine();

            while (line != null) {
                sb.append(line);
                sb.append(System.lineSeparator());
                line = br.readLine();
            }
            e = sb.toString();
        } 
        finally {
            br.close();
        }
        
        int      total = 0;
        int      first = 0;
        String[] v     = e.split("\n");
        String   u     = "";
        
        for (int i = 0; i < v.length; i++)
        {
            u = v[i];
            
            if (u.substring(0,1).equals(t))
            {
                if (first == 0) 
                {
                    first = i;
                }
                total = i;                
            }
        }
        
        if (defined_word_by_ai.isEmpty())
        {
            defined_word_by_ai = v[randInt(first, total)];
        }        
       
        char[] ch = defined_word_by_ai.toCharArray();  
        
        listModel.addElement(ch[global_count] + ":" + t);
        
        // -------------------------------------------------------------------;
        
        String[] j     = e.split("\n");
        String   q     = "";
        
        int      location = 0;
        
        for (int i = 0; i < j.length; i++)
        {
           
            q = j[i];
            
            location = j[i].lastIndexOf('\r');
          
            if (t.length() == location && j[i].indexOf(t) != -1)
            {
                System.out.println (j[i]);
                JOptionPane.showMessageDialog(null, "You lose!", "gi_cli", JOptionPane.INFORMATION_MESSAGE);
            }          
        }
        
        jList1 = new JList(listModel);
        jScrollPane1.setViewportView(jList1);
        
        global_count++;
            
        if (global_count == ch.length - 1)
        {
            global_count = 0;
            JOptionPane.showMessageDialog(null, "You win!", "gi_cli", JOptionPane.INFORMATION_MESSAGE);
        } 
    }
    
    // -------------------------------------------------------------------------;
       
    public static void main(String args[]) throws IOException 
    {                
        gi_cli c = new gi_cli();
        c.setVisible(true);
        c.initComponents();        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    
}
